version: "3.9"

services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard-home
    restart: unless-stopped

    ports:
      - "3000:3000"
      - "80:80"
      - "443:443"
      - "53:53/tcp"
      - "53:53/udp"

    volumes:
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
